variables:
  - group: InfoSec-SecurityResults
  - name: tags
    value: production,externalfacing

jobs:
  - template: fluentui-android-compliance.yml

  - job: Build
    pool:
      vmImage: ubuntu-latest
    variables:
      - name: BUILDSECMON_OPT_IN
        value: true
    steps:
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        options: '-PappCenterSecret=$(appCenterSecret) -PsigningKeyPassword=$(signingKeyPassword) -PsigningKeyStorePassword=$(signingKeyStorePassword)'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(jdkVersion)'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
      
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.sourcesdirectory)/FluentUI.Demo/build/outputs/apk/dogfood/release/FluentUI.Demo-dogfood-release.apk'
        artifact: 'dogfood'
        publishLocation: 'pipeline'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.sourcesdirectory)/dogfood-release-notes.txt'
        artifact: 'notes'
        publishLocation: 'pipeline'
